### ISSUE TITLE
图片相似度计算的时候不准

### ISSUE THREAD

**Issue by YeDongaidiiqu** [Comdex/imgo#6]
完全不相关的两张图片相似度竟然 0.9295204927050034

**Comment by Comdex** [comment]
可以提供一下你的图片和代码例子吗？

**Comment by YeDongaidiiqu** [comment]
![aa](https://user-images.githubusercontent.com/25131877/67663903-776a0b00-f9a1-11e9-95c0-d9061f652d96.png)

![cc](https://user-images.githubusercontent.com/25131877/67663937-8cdf3500-f9a1-11e9-9ecc-d38c1fd749eb.png)

![image](https://user-images.githubusercontent.com/25131877/67663868-628d7780-f9a1-11e9-8986-5e2d1a9e6cf0.png)

![image](https://user-images.githubusercontent.com/25131877/67663989-a4b6b900-f9a1-11e9-892c-100f942ace49.png)

**Comment by Comdex** [comment]
主要是相似度计算函数中使用的源图片矩阵不够大，只要调大矩阵就可以了。
